### ISSUE TITLE
Folder permessions

### ISSUE THREAD

**Issue by nagayev** [vesln/temporary#32]
Why you are using this code`fs.mkdirSync(path.normalize(dirname), 0777)` ?
Creating folder with 0777 permession is danger.
Source:
https://github.com/vesln/temporary/blob/master/lib/dir.js#L38
UPDATE: PR #33

**Comment by willscott** [comment]
The requested mode will be modulated by the process umask, so by requesting 777 The directory is created with the default permissions as specified by the system.
(so note that a work-around to this would be to set a more restrictive [`process.umask`](https://nodejs.org/api/process.html#process_process_umask_mask) when using this library.

Requesting more restrictive permissions could break existing users of the library, so would need to be released as a major version bump. Would there be a reason to do so for directories but not files?

**Comment by nagayev** [comment]
@willscott  No. I forgot about files.

**Comment by nagayev** [comment]
@willscott Should I create another PR for files or just add commit to this?

**Comment by willscott** [comment]
Add commits to this PR.

It looks like golang's standard library temporary defaults to 0600 for files and 0700 for directories ([ref](https://golang.org/src/io/ioutil/tempfile.go)). Probably worth checking other languages to see if there's general consensus for default permission masks.

**Comment by nagayev** [comment]
@willscott Okey.
I will push after weekend.

**Comment by nagayev** [comment]
@willscott Well, I pushed last commit to my fork.

**Comment by nagayev** [comment]
@willscott ping
